services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Autoload all services
  OliverKroener\OkExchange365\:
    resource: '../Classes/*'
    exclude: '../Classes/Mail/Transport/Exchange365Transport.php'



