services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Set an alias for the TYPO3 MailerInterface to use your custom mailer
  TYPO3\CMS\Core\Mail\MailerInterface:
   alias: OliverKroener\OkExchange365\Mail\Exchange365Mailer
   public: true

