services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Autoload all services
  OliverKroener\OkExchange365\:
    resource: '../Classes/*'
    exclude: '../Classes/Mail/Transport/Exchange365Transport.php'

# Register your custom mailer service
 # OliverKroener\OkExchange365\Mail\Transport\Exchange365Transport:
 #   args:
 #     $mailSettings:
 #   calls:
 #     - method: 'setEventDispatcher'
 #       arguments:
 #         - '@event_dispatcher'
 #   public: true     
  #  tags:
  #    - { name: 'mailer.transport', alias: 'exchange365api' }
  #  public: true


